# Multi-Agent Collaboration Configuration
general:
  use_uvloop: true

# LLM配置 - 主协调器使用更强模型
llms:
  master_orchestrator:
    _type: openai
    model_name: "qwen-plus-2025-07-28"
    api_key: "sk-84adb09076ae4093add2d94cc2bfb61c"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    temperature: 0.7
    max_tokens: 2048
  
  expert_executor:
    _type: openai
    model_name: "qwen-plus-2025-07-28"
    api_key: "sk-84adb09076ae4093add2d94cc2bfb61c"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    temperature: 0.7
    max_tokens: 2048

# 工具函数定义
functions:
  # 知识库工具
  insert_docs:
    _type: insert_docs
  retrieve_docs:
    _type: retrieve_docs
  delete_docs:
    _type: delete_docs
  web_search:
    _type: web_search
  no_op_tool:
    _type: no_op_tool

  # 专业智能体 - 文档处理专家
  document_expert:
    _type: tool_calling_agent
    tool_names:
      - insert_docs
      - retrieve_docs
      - delete_docs
    llm_name: expert_executor
    verbose: true
    handle_tool_errors: true
    description: |
      我是一个文档处理专家，用于插入、删除、检索知识库中的文档。
      调用我时，输入格式如下：
      【插入/删除/检索】：具体文档内容，请输入用户的原始文档内容，无需加工

  # 专业智能体 - 联网搜索专家
  search_expert:
    _type: tool_calling_agent
    tool_names:
      - web_search
    llm_name: expert_executor
    verbose: true
    handle_tool_errors: true
    description: |
      我是一个联网搜索专家，当文档处理专家未检索到相关内容或结果相关性不足时，负责从互联网上检索信息并返回相关片段。
      调用我时，输入格式如下：
      【联网搜索】：需要联网搜索的内容

  # 专业智能体 - 回答专家
  answer_expert:
    _type: react_agent
    tool_names:
      - no_op_tool
    llm_name: expert_executor
    verbose: true
    handle_tool_errors: true
    system_prompt: |
      你是一个回答专家，用户会输入一个问题，并且带有文档处理专家检索到的相关知识或者联网搜索专家搜索到的相关背景知识。
      请你对用户原始问题+相关知识进行整理、总结，生成最终回答，请务必保证最终回答准确、全面、专业。
      工具：{tools}
      工具名称：{tool_names}
      此工具仅作占位，你无需调用工具。
      请严格使用以下格式回复：
      Thought: 我现在知晓最终答案
      Final Answer: 你最终生成的回答
    description: |
      我是一个回答专家，负责根据文档处理专家或联网搜索专家返回的内容进行整理、总结，生成最终回答。
      调用我时，输入格式如下：
      【问题】：用户原始的问题
      【相关背景知识】：文档处理专家或联网搜索专家返回的相关知识

# 主工作流 - 协调所有专家
workflow:
  _type: react_agent
  tool_names: [document_expert, search_expert, answer_expert]
  llm_name: master_orchestrator
  verbose: true
  parse_agent_response_max_retries: 1
  system_prompt: |
    你是一位管理着一个由专业人工智能专家组成的团队的编排大师,负责接收用户请求并决定路由。
    您的团队由以下人员组成：
    1.document_export：文档处理专家
    2.search_expert：联网搜索专家
    3.answer_expert：回答专家
    请严格按照以下规则进行操作：
    - 如果用户请求是“插入文档/删除文档”，将请求交给【document_export】来插入或删除文档。无需加工文档内容。
    - 如果用户请求是“提出问题”，先调用【document_export】进行向量数据库检索。无需加工用户问题内容。
      - 如果文档处理专家返回的内容不足或不相关，再调用【search_expert】进行联网搜索。
    - 将最终检索或联网搜索结果交给【answer_expert】整理并回答。
        
    可用工具：{tools}
    
    你可通过以下两种格式之一进行回应。
    格式1：调用工具回答问题（严格使用）
    请严格使用以下格式来调用工具回答问题：
    Question: 你必须回答的输入问题
    Thought: 你应当始终思考该做什么
    Action: 需要执行的动作，必须是 [{tool_names}] 中的一个
    Action Input: 动作的输入内容（若无需输入，请注明 “动作输入：无”）
    Observation: 等待工具返回结果，切勿假设回应内容
    （此思考 / 动作 / 动作输入 / 观察结果可重复 N 次。）
    
    格式2：直接回答（无需工具时使用）
    当你获得最终答案后，请使用以下格式：
    Thought: 我现在知晓最终答案
    Final Answer: 原始输入问题的最终答案